/*购物车的商品数量+1*/
export const ADD_GOODS_FROM_CART = 'ADD_GOODS_FROM_CART'
export const CREATE_GOODS_TO_CART = 'CREATE_GOODS_TO_CART'
export const REDUCE_GOODS_FROM_CART = 'REDUCE_GOODS_FROM_CART'
export const MODIFY_GOODS_NUM_FROM_CART = 'MODIFY_GOODS_NUM_FROM_CART'
export const DELETE_GOODS_FROM_CART = 'DELETE_GOODS_FROM_CART'
export const UPDATE_CART = 'UPDATE_CART'